export enum Country {
    Spanje = "SPA",
    Frankrijk = "FRA",
    België = "BEL",
    Engeland = "ENG",
    Noorwegen = "NOO",
    Nederland = "NED",
    Duitsland = "DUI",
    Kroatië = "KRO",
    Italië = "ITA",
    Slovenië = "SLOV",
    Zweden = "ZWE",
    Ierland = "IER",
    Letland = "LET",
    Zwitserland = "ZWI",
    Denemarken = "DEN",
    Faeröer = "FAR",
    Hongarije = "HON",
    Oostenrijk = "OOS",
    Estland = "EST",
    Polen = "POL",
    Finland = "FIN",
    Servië = "SER",
    Tsjechië = "TSJ",
    Portugal = "POR",
    Luxemburg = "LUX",
    Slowakije = "SLOW",
    Onbekend = "ONBEKEND"
}

export enum CountryFlag {
    SPA = "🇪🇸",
    FRA = "🇫🇷",
    BEL = "🇧🇪",
    ENG = "🏴",
    NOO = "🇳🇴",
    NED = "🇳🇱",
    DUI = "🇩🇪",
    KRO = "🇭🇷",
    ITA = "🇮🇹",
    SLOV = "🇸🇮",
    ZWE = "🇸🇪",
    IER = "🇮🇪",
    LET = "🇱🇻",
    ZWI = "🇨🇭",
    DEN = "🇩🇰",
    FAR = "🇫🇴",
    HON = "🇭🇺",
    OOS = "🇦🇹",
    EST = "🇪🇪",
    POL = "🇵🇱",
    FIN = "🇫🇮",
    SER = "🇷🇸",
    TSJ = "🇨🇿",
    POR = "🇵🇹",
    LUX = "🇱🇺",
    SLOW = "🇸🇰",
    ONBEKEND = ""
}

